config/routes.rb
Rails.application.routes.draw do
  get '/' => 'home#index'
  resources :users do
    resources :photos
  end

  resources :tags, only: [:create, :destroy]
  get '/log-in' => "sessions#new"
  post '/log-in' => "sessions#create"
  get '/log-out' => "sessions#destroy", as: :log_out

  resources :followships, only: [:create, :destroy]
  resources :comments, only: [:create]
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :photo
  belongs_to :user
end

app/models/followship.rb
class Followship < ActiveRecord::Base
end

app/models/photo.rb
class Photo<ActiveRecord::Base
  belongs_to :user
  has_many :tags, :dependent => :destroy
  has_many :comments, :dependent => :destroy

  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  validates :title, presence: true

  def is_owned_by?(user_id)
    self.user_id == user_id
  end
end

app/models/tag.rb
class Tag<ActiveRecord::Base
  belongs_to :user
  belongs_to :photo
end

app/models/user.rb
class User<ActiveRecord::Base
  has_many :photos
  has_many :tags
  attr_accessor :password
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  validates_confirmation_of :password
  before_save :encrypt_password
  validates :email, uniqueness: true

  validates :email, :presence => true
  def encrypt_password
    self.password_salt = BCrypt::Engine.generate_salt
    self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
  end

  def is_email?
    self.email.include?('@') && self.email.include?('.')
  end

  def self.authenticate(email, password)
    user = User.where(email: email).first
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

  def follows?(other_user)
    Followship.exists?(follower_id: self.id, followed_id: other_user.id)
  end
  
  def followees
    followee_ids = Followship.where(follower_id: self.id).map(&:followed_id)
    User.find(followee_ids)
  end

  def all_photos
    users = [self] + self.followees
    Photo.where(user_id: users.map(&:id)).order(created_at: :desc)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    Comment.create!(text: comment_params[:text],
                    photo_id: comment_params[:photo_id],
                    user_id: session[:user_id])
    redirect_to :back
  end

  private
  def comment_params
    params.require(:comment).permit(:text, :photo_id)
  end
end

app/controllers/followships_controller.rb
class FollowshipsController < ApplicationController
  def create
    followship = Followship.create!(followship_params)
    redirect_to user_path(followship.followed_id)
  end

  private
  def followship_params
    params.require(:followship).permit(:follower_id,
                                       :followed_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def create
    @user = User.find(params[:user_id])
    if params[:photo] == nil

      flash[:alert] = "Please upload a photo"
      redirect_to :back
    else
      @photo = Photo.create(photo_params)
      if @photo.valid?
        @photo.user_id = @user.id
        @photo.save
        flash[:notice] = "Successfully uploaded a photo"
        redirect_to user_path(@user)
      else
        flash[:alert] = "Missing fields"
        redirect_to :back
      end
    end
  end

  def new
    @user = User.find(params[:user_id])
    @photo = Photo.create()
  end

  def destroy
    photo = Photo.find(params[:id])
    if photo.user.id == session[:user_id]
      photo.destroy!
    end
    redirect_to :back
  end

  def show
    @photo = Photo.find(params[:id])
    @users = User.all
    @myself = session[:user_id]
    @tag = Tag.new
  end

  private
  def photo_params
    params.require(:photo).permit(:image, :title)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.authenticate(params[:email], params[:password])
    if @user
      flash[:notice] = "You've been logged in."
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      flash[:alert] = "There was a problem logging you in!"
      redirect_to log_in_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You've been logged out successfully."
    redirect_to "/"
  end

end

app/controllers/tags_controller.rb
class TagsController<ActionController::Base
  def new
    redirect_to "/"
  end

  def create
    @user = User.find(params[:tag][:user_id])
    @tag = Tag.create({user_id: params[:tag][:user_id], photo_id: params[:tag][:photo_id]})
    redirect_to user_path(session[:user_id])
  end




end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    @user = User.new(user_params)
    @user.valid?
    if !@user.is_email?
      flash[:alert] = "Input a properly formatted email."
      redirect_to :back
    elsif @user.errors.messages[:email] != nil
      flash[:notice]= "That email " + @user.errors.messages[:email].first
      redirect_to :back
    elsif @user.save
      flash[:notice]= "Signup successful. Welcome to the site!"
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      flash[:alert] = "There was a problem creating your account. Please try again."
      redirect_to :back
    end
  end

  def new
  end

  def show
    @myself = session[:user_id]
    @users = User.all
    @user = User.find(params[:id])
    @tag = Tag.new
  end

  def index
    @users = User.all
    @myself = User.find(session[:user_id])
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.haml
%h1 Treegram
%h2 Your Favorite Tree Photosharing Service
.row
  .col-sm-4
    = link_to 'Login', log_in_path, class: ["btn", "btn-success", 'btn-lg']
    = link_to 'Sign Up', new_user_path, class: ['btn', 'btn-success', 'btn-lg']
  .col-sm-7
    = image_tag "background.jpg"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title PhotoShare
    %link{:href => "http://fonts.googleapis.com/css?family=Open+Sans+Condensed:300", :rel => "stylesheet", :type => "text/css"}/
    %link{:href => "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css", :rel => "stylesheet"}/
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .container
      = flash[:alert]
      = flash[:notice]
      = yield

app/views/photos/new.html.haml
%h1 Add a Photo
= form_for Photo.new(), :url => user_photos_path, :html => {:multipart => true} do |form|
  = form.label :title
  = form.text_field :title
  = form.file_field :image
  = form.submit 'Upload'

app/views/photos/show.html.haml
%a#closeLink Close

- if @photo.is_owned_by?(@myself)
  = form_for @photo, method: :delete, url: user_photo_path(User.find(@myself), @photo) do |f|
    = f.submit "Delete"
%h3= @photo.title
= image_tag @photo.image.url(:medium)
= form_for @tag do |f|
  = f.hidden_field :photo_id, value: @photo.id
  = f.collection_select :user_id, @users, :id, :email
  = f.submit "Tag User"
- @photo.tags.each do |tag|
  = tag.user.email

%h4 Comments
%ul
- @photo.comments.each do |comment|
  %li{style: 'list-style-type: none;'}
    %strong= comment.user.email
    = comment.text
= form_for Comment.new do |f|
  = f.hidden_field :photo_id, value: @photo.id
  = f.text_field :text, required: true
  = f.submit "Comment"

app/views/users/index.html.haml
%ul
  - @users.each do |user|
    - if session[:user_id] != user.id
      %li.user-follow-row
        = user.email
        - unless @myself.follows?(user)
          = form_for Followship.new(), :url => followships_path do |form|
            = form.hidden_field :follower_id, value: session[:user_id]
            = form.hidden_field :followed_id, value: user.id
            = form.submit 'Follow'

app/views/users/new.html.haml
%h1 Sign Up
= form_for User.new, class: "form-inline" do |f|
  = f.label :email
  = f.text_field :email
  = f.label :password
  = f.password_field :password
  = f.label :password_confirmation
  = f.password_field :password_confirmation
  %br/
  = f.label :avatar, 'Upload Avatar'
  = f.file_field :avatar
  %br/
  = f.submit "Sign Up"

app/views/users/show.html.haml
.row.top_row
  .col-sm-6.user_att
    %h2= @user.email
    - if @user.avatar_file_name
      = image_tag @user.avatar.url(:thumb)
  .col-sm-6
    = link_to 'Logout', log_out_path, class: ['btn', 'btn-danger', 'logout_btn']
  .row
    = link_to 'Add Photo', new_user_photo_path(@user), class: ['btn', 'btn-success', 'add_photo_btn']
%br/
%br/
%br/
%br/
%br/
%br/
%br/
%br/
%br/
%br/
.row
  = link_to 'Show All Users', users_path, class: ['btn', 'btn-info']
#photos.row
  - ([@user] + @user.followees).each do |user|
    - unless user.photos.empty?
      .well.col-sm-4.slideshow[user]
        %h3= user.email
        .slide
          %h4.title= user.photos.last.title
          = image_tag user.photos.last.image.url(:medium), data: { "modal-url" => user_photo_path(user, user.photos.last) }
        .slides
          - user.photos.each do |photo|
            = image_tag photo.image.url(:medium), data: { "modal-url" => user_photo_path(user, photo) }